# Generated by Django 5.1.6 on 2025-02-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='followers',
            table='FoLoWers',
        ),
    ]
