# Generated by Django 5.1.6 on 2025-02-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalApp', '0003_alter_followers_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name': 'obeeeemeee'},
        ),
    ]
