# Generated by Django 5.1.6 on 2025-02-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalApp', '0004_alter_followers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name': 'FollOOWWWERRS'},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default_photo.jpeg', upload_to=''),
        ),
    ]
