# Generated by Django 5.1.6 on 2025-02-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalApp', '0005_alter_followers_options_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_photo.jpeg', upload_to='users_posts_images'),
        ),
    ]
