# Generated by Django 5.1.6 on 2025-03-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalApp', '0011_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='no title', max_length=100),
        ),
    ]
