# Generated by Django 5.1.6 on 2025-03-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalApp', '0013_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users_posts_images'),
        ),
    ]
