# Generated by Django 5.1.6 on 2025-04-11 12:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalApp', '0017_alter_followers_from_user_alter_followers_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('from_user', 'to_user')},
        ),
    ]
