# Generated by Django 5.1.6 on 2025-03-06 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='def_ava.jpeg', upload_to='users_avatars'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='bio', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='.', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
