# Generated by Django 5.1.6 on 2025-03-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0003_alter_userprofile_bio_alter_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='users_avatars/def_ava.jpeg', upload_to='users_avatars'),
        ),
    ]
