# Generated by Django 5.1.6 on 2025-03-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='users_avatars/def_ava.jpg', upload_to='users_avatars'),
        ),
    ]
